const STORAGE_KEY="statuslite-demo-v1";
const defaultState={services:[{id:crypto.randomUUID(),name:"Public API",description:"api.statuslite.dev",status:"operational",uptime:99.99},{id:crypto.randomUUID(),name:"Web Dashboard",description:"app.statuslite.dev",status:"operational",uptime:99.97},{id:crypto.randomUUID(),name:"Auth Service",description:"authentication & sessions",status:"operational",uptime:100},{id:crypto.randomUUID(),name:"Background Jobs",description:"queues & scheduled workers",status:"degraded",uptime:99.86}],incidents:[{id:crypto.randomUUID(),title:"Elevated queue processing time",service:"Background Jobs",state:"monitoring",message:"Queue latency briefly increased after a worker restart. Processing has recovered and we're monitoring the service.",timestamp:new Date(Date.now()-38*60*1000).toISOString()},{id:crypto.randomUUID(),title:"Dashboard deploy completed",service:"Web Dashboard",state:"resolved",message:"A routine frontend deployment completed successfully with no user impact.",timestamp:new Date(Date.now()-26*60*60*1000).toISOString()}],uptimeSeries:[99.99,100,99.98,99.94,100,99.99,99.97]};
let state=loadState();
const $=s=>document.querySelector(s),servicesList=$("#servicesList"),incidentsList=$("#incidentsList"),serviceTemplate=$("#serviceTemplate"),overallDot=$("#overallDot"),overallLabel=$("#overallLabel"),clockValue=$("#clockValue"),servicesCount=$("#servicesCount"),operationalCount=$("#operationalCount"),avgUptime=$("#avgUptime"),openIncidents=$("#openIncidents"),uptimeSummary=$("#uptimeSummary"),uptimeBars=$("#uptimeBars"),serviceModal=$("#serviceModal"),incidentModal=$("#incidentModal"),serviceForm=$("#serviceForm"),incidentForm=$("#incidentForm"),incidentService=$("#incidentService");
$("#openServiceModalBtn").addEventListener("click",()=>{serviceForm.reset();$("#serviceUptime").value="99.99";serviceModal.showModal()});
$("#openIncidentModalBtn").addEventListener("click",()=>{populateIncidentServices();incidentForm.reset();incidentModal.showModal()});
$("#resetDemoBtn").addEventListener("click",()=>{if(!confirm("Reset StatusLite to the original demo data?"))return;state=structuredClone(defaultState);saveState();render()});
document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.close).close()));
serviceForm.addEventListener("submit",e=>{e.preventDefault();state.services.push({id:crypto.randomUUID(),name:$("#serviceName").value.trim(),description:$("#serviceDescription").value.trim(),status:$("#serviceStatus").value,uptime:Number($("#serviceUptime").value)});saveState();render();serviceModal.close()});
incidentForm.addEventListener("submit",e=>{e.preventDefault();state.incidents.unshift({id:crypto.randomUUID(),title:$("#incidentTitle").value.trim(),service:incidentService.value,state:$("#incidentState").value,message:$("#incidentMessage").value.trim(),timestamp:new Date().toISOString()});saveState();render();incidentModal.close()});
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function render(){renderServices();renderIncidents();renderMetrics();renderUptime();populateIncidentServices()}
function renderServices(){servicesList.innerHTML="";if(!state.services.length){servicesList.innerHTML='<div class="empty-state">No services yet. Add one to start tracking it.</div>';return}state.services.forEach(service=>{const node=serviceTemplate.content.cloneNode(true),dot=node.querySelector(".service-status-dot"),name=node.querySelector(".service-name"),desc=node.querySelector(".service-description"),uptime=node.querySelector(".service-uptime"),select=node.querySelector(".service-status-select"),del=node.querySelector(".delete-btn");dot.classList.add(service.status);name.textContent=service.name;desc.textContent=service.description;uptime.textContent=`${service.uptime.toFixed(2)}%`;select.value=service.status;select.addEventListener("change",()=>{service.status=select.value;saveState();render()});del.addEventListener("click",()=>{if(!confirm(`Delete ${service.name}?`))return;state.services=state.services.filter(i=>i.id!==service.id);saveState();render()});servicesList.appendChild(node)})}
function renderIncidents(){incidentsList.innerHTML="";if(!state.incidents.length){incidentsList.innerHTML='<div class="empty-state">No incidents logged.</div>';return}state.incidents.slice(0,6).forEach(incident=>{const item=document.createElement("article");item.className=`incident ${incident.state==="resolved"?"resolved":"open"}`;item.innerHTML=`<div class="incident-top"><h3></h3><span class="incident-badge"></span></div><p></p><div class="incident-meta"></div>`;item.querySelector("h3").textContent=incident.title;item.querySelector(".incident-badge").textContent=incident.state;item.querySelector("p").textContent=incident.message;item.querySelector(".incident-meta").textContent=`${incident.service} · ${formatRelativeTime(incident.timestamp)}`;incidentsList.appendChild(item)})}
function renderMetrics(){servicesCount.textContent=state.services.length;const operational=state.services.filter(s=>s.status==="operational").length;operationalCount.textContent=operational;const avg=state.services.length?state.services.reduce((sum,i)=>sum+Number(i.uptime||0),0)/state.services.length:0;avgUptime.textContent=`${avg.toFixed(2)}%`;openIncidents.textContent=state.incidents.filter(i=>i.state!=="resolved").length;const statuses=state.services.map(s=>s.status),overall=statuses.includes("outage")?"outage":statuses.includes("degraded")?"degraded":"operational",labels={operational:"All systems operational",degraded:"Some systems degraded",outage:"Major service disruption"};overallDot.className=`status-dot ${overall}`;overallLabel.textContent=labels[overall]}
function renderUptime(){uptimeBars.innerHTML="";const values=state.uptimeSeries||defaultState.uptimeSeries,labels=getLastSevenDayLabels();values.forEach((value,index)=>{const day=document.createElement("div");day.className="uptime-day";day.title=`${labels[index]}: ${value.toFixed(2)}%`;const track=document.createElement("div");track.className="uptime-track";const fill=document.createElement("div");fill.className="uptime-fill";fill.style.height=`${Math.min(100,Math.max(32,100-(100-value)*110))}%`;const label=document.createElement("small");label.textContent=labels[index];track.appendChild(fill);day.append(track,label);uptimeBars.appendChild(day)});uptimeSummary.textContent=`${(values.reduce((s,v)=>s+v,0)/values.length).toFixed(2)}%`}
function populateIncidentServices(){incidentService.innerHTML="";state.services.forEach(service=>{const o=document.createElement("option");o.value=service.name;o.textContent=service.name;incidentService.appendChild(o)})}
function formatRelativeTime(iso){const diff=Date.now()-new Date(iso).getTime(),minutes=Math.max(1,Math.round(diff/60000));if(minutes<60)return`${minutes} min ago`;const hours=Math.round(minutes/60);if(hours<24)return`${hours}h ago`;return`${Math.round(hours/24)}d ago`}
function getLastSevenDayLabels(){const labels=[],f=new Intl.DateTimeFormat("en",{weekday:"short"});for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);labels.push(f.format(d))}return labels}
function updateClock(){clockValue.textContent=new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date())}
updateClock();setInterval(updateClock,1000);render();
